"""
dashboard.py - Patent Intelligence Dashboard
Run with: streamlit run dashboard.py
Reads from pre-computed result tables in patents.db (generated by scripts 03 & 04)
for fast loading — no heavy GROUP BY queries at runtime.
"""

import os
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use("Agg")
import seaborn as sns
from sqlalchemy import create_engine, text, inspect

BASE_DIR    = os.path.abspath(os.path.dirname(__file__))
DB_PATH = os.path.join(os.path.dirname(__file__), "data/db/patents_results.db")
REPORTS_DIR = os.path.join(BASE_DIR, "reports")

st.set_page_config(page_title="Patent Intelligence Dashboard",
                   page_icon="🔬", layout="wide")

@st.cache_resource
def get_engine():
    return create_engine(f"sqlite:///{DB_PATH}", echo=False)

def table_exists(name):
    try:
        insp = inspect(get_engine())
        return name in insp.get_table_names()
    except Exception:
        return False

@st.cache_data
def load_table(table_name):
    try:
        with get_engine().connect() as conn:
            return pd.read_sql_query(text(f"SELECT * FROM {table_name}"), conn)
    except Exception:
        return pd.DataFrame()

@st.cache_data
def simple_query(sql):
    try:
        with get_engine().connect() as conn:
            return pd.read_sql_query(text(sql), conn)
    except Exception:
        return pd.DataFrame()

# ── Sidebar ───────────────────────────────────────────────
st.sidebar.title("🔬 Patent Intelligence")
st.sidebar.markdown("Global Patent Data Explorer")
top_n      = st.sidebar.slider("Top N results", 5, 50, 15)
year_range = st.sidebar.slider("Year range", 1976, 2025, (2000, 2025))

# ── Title ─────────────────────────────────────────────────
st.title("🔬 Global Patent Intelligence Dashboard")
st.caption("Data: USPTO PatentsView Granted Patent Disambiguated Data")
st.info("📊 Dataset: 9,434,703 patents | 4,294,034 inventors | 572,495 companies | 1976–2025")
# ── KPIs ──────────────────────────────────────────────────
c1, c2, c3 = st.columns(3)
c1.metric("Total Patents",     "9,434,703")
c2.metric("Unique Inventors",  "4,294,034")
c3.metric("Unique Companies",  "572,495")

st.markdown("---")

# ── Tabs ──────────────────────────────────────────────────
tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
    "📈 Trends", "👤 Inventors", "🏢 Companies",
    "🌍 Countries", "⚡ Innovation Velocity", "🔬 Technology"
])

sns.set_theme(style="whitegrid")

# ═══════════════════════════════════════════════
# TAB 1 – TRENDS
# ═══════════════════════════════════════════════
with tab1:
    st.subheader("Patents Granted Per Year")
    df_yr = load_table("result_q4_yearly_trends")
    if not df_yr.empty:
        df_yr = df_yr[(df_yr["year"] >= year_range[0]) & (df_yr["year"] <= year_range[1])]
        fig, ax = plt.subplots(figsize=(12, 4))
        ax.plot(df_yr["year"], df_yr["patent_count"], color="#2196F3", linewidth=2)
        ax.fill_between(df_yr["year"], df_yr["patent_count"], alpha=0.15, color="#2196F3")
        ax.set_xlabel("Year"); ax.set_ylabel("Patents")
        st.pyplot(fig); plt.close(fig)
        st.dataframe(df_yr, use_container_width=True)

    # China vs USA
    st.subheader("🇺🇸 USA vs 🇨🇳 China Patent Race")
    race = load_table("result_china_vs_usa")
    if not race.empty:
        us = race[race["country"] == "US"]
        cn = race[race["country"] == "CN"]
        fig, ax = plt.subplots(figsize=(12, 4))
        ax.plot(us["year"], us["patent_count"], color="#3C78D8", linewidth=2.5, label="USA")
        ax.fill_between(us["year"], us["patent_count"], alpha=0.1, color="#3C78D8")
        ax.plot(cn["year"], cn["patent_count"], color="#E53935", linewidth=2.5, label="China")
        ax.fill_between(cn["year"], cn["patent_count"], alpha=0.1, color="#E53935")
        ax.set_xlabel("Year"); ax.set_ylabel("Patents"); ax.legend(fontsize=11)
        ax.set_title("The Patent Race: USA vs China (1990–Present)", fontweight="bold")
        merged = us.merge(cn, on="year", suffixes=("_us", "_cn"))
        cross  = merged[merged["patent_count_cn"] >= merged["patent_count_us"]]
        if not cross.empty:
            yr = int(cross.iloc[0]["year"])
            ax.axvline(x=yr, color="gray", linestyle=":", linewidth=1.5)
            ax.annotate(f"Crossover\n{yr}", xy=(yr, ax.get_ylim()[1]*0.8),
                        fontsize=9, color="gray", ha="center")
        st.pyplot(fig); plt.close(fig)
    else:
        st.info("Run script 03 to generate this data.")

# ═══════════════════════════════════════════════
# TAB 2 – INVENTORS
# ═══════════════════════════════════════════════
with tab2:
    st.subheader(f"Top {top_n} Inventors")
    df_inv = load_table("result_q1_top_inventors").head(top_n)
    if not df_inv.empty:
        fig, ax = plt.subplots(figsize=(10, max(4, top_n * 0.4)))
        data = df_inv.sort_values("patent_count")
        ax.barh(data["name"].astype(str), data["patent_count"],
                color=sns.color_palette("Blues_d", len(data)))
        ax.set_xlabel("Patents")
        st.pyplot(fig); plt.close(fig)
        st.dataframe(df_inv[["name","country","patent_count"]], use_container_width=True)

    st.subheader("Inventor Rankings (Window Functions)")
    df_rank = load_table("result_q7_ranking").head(top_n)
    if not df_rank.empty:
        st.dataframe(df_rank, use_container_width=True)

# ═══════════════════════════════════════════════
# TAB 3 – COMPANIES
# ═══════════════════════════════════════════════
with tab3:
    st.subheader(f"Top {top_n} Companies")
    df_co = load_table("result_q2_top_companies").head(top_n)
    if not df_co.empty:
        fig, ax = plt.subplots(figsize=(12, max(4, top_n * 0.4)))
        data = df_co.sort_values("patent_count")
        names = [str(n)[:40] if n else "Unknown" for n in data["name"]]
        ax.barh(names, data["patent_count"], color=sns.color_palette("Greens_d", len(data)))
        ax.set_xlabel("Patents")
        st.pyplot(fig); plt.close(fig)
        st.dataframe(df_co[["name","country","patent_count"]], use_container_width=True)

# ═══════════════════════════════════════════════
# TAB 4 – COUNTRIES
# ═══════════════════════════════════════════════
with tab4:
    st.subheader("Patents by Country")
    df_ct = load_table("result_q3_countries").head(top_n)
    if not df_ct.empty:
        col1, col2 = st.columns(2)
        with col1:
            fig, ax = plt.subplots(figsize=(7, 6))
            top10  = df_ct.head(10)
            others = df_ct.iloc[10:]["patent_count"].sum()
            labels = list(top10["country"]) + (["Others"] if others else [])
            sizes  = list(top10["patent_count"]) + ([others] if others else [])
            ax.pie(sizes, labels=labels, autopct="%1.1f%%", startangle=140,
                   colors=sns.color_palette("tab20", len(labels)))
            ax.set_title("Patent Share by Country", fontweight="bold")
            st.pyplot(fig); plt.close(fig)
        with col2:
            st.dataframe(df_ct, use_container_width=True)

    st.subheader("Top Inventor Per Country (CTE Query Result)")
    df_cte = load_table("result_q6_cte")
    if not df_cte.empty:
        st.dataframe(df_cte, use_container_width=True)

# ═══════════════════════════════════════════════
# TAB 5 – INNOVATION VELOCITY
# ═══════════════════════════════════════════════
with tab5:
    st.subheader("Fastest Accelerating Companies")
    st.markdown("Companies ranked by how much their patent filing has **accelerated** (2015–2025 vs 2000–2014)")
    df_vel = load_table("result_innovation_velocity").head(top_n)
    if not df_vel.empty:
        fig, ax = plt.subplots(figsize=(11, max(4, top_n * 0.4)))
        data = df_vel.sort_values("velocity_ratio")
        ax.barh([str(n)[:40] for n in data["name"]], data["velocity_ratio"],
                color=sns.color_palette("Oranges_d", len(data)))
        ax.axvline(x=1, color="red", linestyle="--", linewidth=1, label="No change (1x)")
        ax.set_xlabel("Velocity Ratio (recent ÷ historical)")
        ax.set_title("Innovation Velocity: 2015–2025 vs 2000–2014", fontweight="bold")
        ax.legend()
        st.pyplot(fig); plt.close(fig)
        st.dataframe(df_vel, use_container_width=True)
    else:
        st.info("Run script 03 to generate this data.")

# ═══════════════════════════════════════════════
# TAB 6 – TECHNOLOGY (CPC)
# ═══════════════════════════════════════════════
with tab6:
    st.subheader("Technology Area Trends Over Time")
    df_tech = load_table("result_technology_trends")
    if not df_tech.empty:
        pivot = df_tech.pivot_table(index="year", columns="technology_area",
                                    values="patent_count", aggfunc="sum").fillna(0)
        top_areas = pivot.sum().nlargest(6).index
        pivot = pivot[top_areas]
        pivot = pivot[(pivot.index >= year_range[0]) & (pivot.index <= year_range[1])]
        fig, ax = plt.subplots(figsize=(13, 5))
        for col in pivot.columns:
            ax.plot(pivot.index, pivot[col], linewidth=2, label=col)
        ax.set_xlabel("Year"); ax.set_ylabel("Patents")
        ax.set_title("Technology Area Patent Trends", fontweight="bold")
        ax.legend(loc="upper left", fontsize=8)
        st.pyplot(fig); plt.close(fig)
        st.dataframe(df_tech, use_container_width=True)
    else:
        st.info("Run script 04 to generate technology data.")

    st.subheader("Technology Share (All Years)")
    df_share = load_table("result_technology_share")
    if not df_share.empty:
        col1, col2 = st.columns(2)
        with col1:
            fig, ax = plt.subplots(figsize=(7, 6))
            top8   = df_share.head(8)
            others = df_share.iloc[8:].iloc[:, 1].sum() if len(df_share) > 8 else 0
            labels = list(top8.iloc[:, 0]) + (["Others"] if others else [])
            sizes  = list(top8.iloc[:, 1]) + ([others] if others else [])
            ax.pie(sizes, labels=labels, autopct="%1.1f%%", startangle=140,
                   colors=sns.color_palette("tab10", len(labels)))
            ax.set_title("Technology Share", fontweight="bold")
            st.pyplot(fig); plt.close(fig)
        with col2:
            st.dataframe(df_share, use_container_width=True)

    st.subheader("Country Technology Specialisation")
    df_spec = load_table("result_country_tech_specialisation")
    if not df_spec.empty:
        pivot2 = df_spec.pivot_table(index="country", columns="technology_area",
                                     values="patents", aggfunc="sum").fillna(0)
        fig, ax = plt.subplots(figsize=(13, 6))
        sns.heatmap(pivot2, annot=True, fmt=".0f", cmap="YlOrRd", ax=ax,
                    linewidths=0.5, cbar_kws={"label": "Patents"})
        ax.set_title("Technology Specialisation by Country", fontweight="bold")
        plt.xticks(rotation=30, ha="right")
        plt.tight_layout()
        st.pyplot(fig); plt.close(fig)
    else:
        st.info("Run script 04 to generate specialisation data.")

st.markdown("---")
st.caption("USPTO PatentsView | Pipeline: scripts 01 → 02 → 03 → 04 | Dashboard: streamlit run dashboard.py")